apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermanagement1
  template:
    metadata:
      labels:
        app: usermanagement1
    spec:
      containers:
        - name: usermanagement1
          image: frawatson/usermanagement1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
