apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermanagement
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      containers:
        - name: usermanagement
          image: frawatson/usermanagement:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
